/**
 * FrontMatterPlugin - YAML (or TOML) front matter as a key/value table
 *
 * Nearly every SKILL.md, agent file and plan document generated by an LLM
 * opens with a `---` block of metadata. Rendered as plain markdown that is a
 * horizontal rule followed by a paragraph of `name: foo`. Here it becomes a
 * collapsible table at the top of the document instead.
 *
 * Only a document's first lines can be front matter, and only when they parse
 * as a YAML mapping (TOML between `+++` is shown as it is written). Anything
 * else is left to the ordinary rules, so a document that merely starts with
 * a horizontal rule is unaffected.
 */
import { load as parseYaml } from 'js-yaml';

import { BUILTIN_PLUGINS } from '@shared/constants';

import type { MarkdownPlugin, PluginMetadata, PluginPreferencesSchema } from '@shared/types';
import type { PluginThemeDeclaration } from '../../themes/types';
import type MarkdownIt from 'markdown-it';
import type StateBlock from 'markdown-it/lib/rules_block/state_block.mjs';
import type Token from 'markdown-it/lib/token.mjs';

/** Token type produced for the front matter block */
export const FRONT_MATTER_TOKEN = 'front_matter';

/** What the block rule records on the token */
export interface FrontMatterMeta {
  kind: 'yaml' | 'toml';
  /** The parsed mapping, for YAML; null for TOML, which is shown raw */
  data: Record<string, unknown> | null;
}

/**
 * Preferences for the front matter plugin
 */
export interface FrontMatterPreferences {
  /** Whether the block starts open */
  expanded: boolean;
}

export const DEFAULT_FRONT_MATTER_PREFERENCES: FrontMatterPreferences = {
  expanded: true,
};

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value) && !(value instanceof Date);
}

/**
 * The block rule alone, for parsers that need to see the front matter as one
 * block without rendering it (the edit-mode slicer).
 */
export function frontMatterBlockRule(md: MarkdownIt): void {
  md.block.ruler.before(
    'table',
    FRONT_MATTER_TOKEN,
    (state: StateBlock, startLine: number, endLine: number, silent: boolean): boolean => {
      // Front matter opens the document and nothing else
      if (startLine !== 0 || state.tShift[0] !== 0) return false;

      const lineText = (line: number): string =>
        state.src.slice(state.bMarks[line], state.eMarks[line]);

      const opener = lineText(0).trimEnd();
      let kind: FrontMatterMeta['kind'];
      let closers: string[];
      if (opener === '---') {
        kind = 'yaml';
        closers = ['---', '...'];
      } else if (opener === '+++') {
        kind = 'toml';
        closers = ['+++'];
      } else {
        return false;
      }

      let closeLine = -1;
      for (let line = 1; line < endLine; line++) {
        if (closers.includes(lineText(line).trimEnd())) {
          closeLine = line;
          break;
        }
      }
      if (closeLine === -1) return false;

      const body = state.src.slice(state.bMarks[1], state.eMarks[closeLine - 1]);

      let data: Record<string, unknown> | null = null;
      if (kind === 'yaml') {
        try {
          const parsed: unknown = parseYaml(body);
          // A rule, some prose and another rule is markdown, not metadata
          if (!isPlainObject(parsed)) return false;
          data = parsed;
        } catch {
          return false;
        }
      }

      if (silent) return true;

      const token = state.push(FRONT_MATTER_TOKEN, '', 0);
      token.block = true;
      token.content = body;
      token.info = kind;
      token.map = [0, closeLine + 1];
      token.meta = { kind, data } satisfies FrontMatterMeta;
      token.attrSet('data-source-lines', `0-${closeLine + 1}`);

      state.line = closeLine + 1;
      return true;
    },
    { alt: [] }
  );
}

/**
 * Front matter plugin
 */
export class FrontMatterPlugin implements MarkdownPlugin {
  metadata: PluginMetadata = {
    id: BUILTIN_PLUGINS.FRONT_MATTER,
    name: 'Front Matter',
    version: '1.0.0',
    description: 'Shows YAML front matter as a collapsible key/value table',
  };

  private preferences: FrontMatterPreferences = { ...DEFAULT_FRONT_MATTER_PREFERENCES };

  apply(md: MarkdownIt): void {
    frontMatterBlockRule(md);
    md.renderer.rules[FRONT_MATTER_TOKEN] = (tokens: Token[], idx: number): string =>
      this.renderToken(tokens[idx]!);
  }

  private renderToken(token: Token): string {
    const meta = token.meta as FrontMatterMeta;
    const lines = token.attrGet('data-source-lines');
    const linesAttr = lines ? ` data-source-lines="${lines}"` : '';
    const openAttr = this.preferences.expanded ? ' open' : '';

    let body: string;
    let count: string;
    if (meta.data) {
      const keys = Object.keys(meta.data);
      count = `${keys.length} ${keys.length === 1 ? 'field' : 'fields'}`;
      body = this.renderValue(meta.data);
    } else {
      count = meta.kind.toUpperCase();
      body = `<pre class="front-matter-raw">${escapeHtml(token.content)}</pre>`;
    }

    return (
      `<details class="front-matter"${linesAttr}${openAttr}>` +
      `<summary class="front-matter-summary">Front matter<span class="front-matter-count">${count}</span></summary>` +
      `<div class="front-matter-body">${body}</div>` +
      `</details>\n`
    );
  }

  /**
   * Mappings become tables, lists become lists, and scalars are printed.
   * Nesting follows the data, so a list of mappings is a list of tables.
   */
  private renderValue(value: unknown): string {
    if (value === null || value === undefined) {
      return '<span class="front-matter-null">–</span>';
    }
    if (typeof value === 'boolean' || typeof value === 'number' || typeof value === 'bigint') {
      return `<span class="front-matter-scalar front-matter-${typeof value}">${String(value)}</span>`;
    }
    if (value instanceof Date) {
      return `<span class="front-matter-scalar front-matter-date">${value.toISOString()}</span>`;
    }
    if (typeof value === 'string') {
      if (value.includes('\n')) {
        return `<pre class="front-matter-text">${escapeHtml(value)}</pre>`;
      }
      return `<span class="front-matter-scalar front-matter-string">${escapeHtml(value)}</span>`;
    }
    if (Array.isArray(value)) {
      if (value.length === 0) return '<span class="front-matter-null">[]</span>';
      const items = value.map((item) => `<li>${this.renderValue(item)}</li>`).join('');
      return `<ul class="front-matter-list">${items}</ul>`;
    }
    if (isPlainObject(value)) {
      const entries = Object.entries(value);
      if (entries.length === 0) return '<span class="front-matter-null">{}</span>';
      const rows = entries
        .map(
          ([key, item]) =>
            `<tr><th scope="row">${escapeHtml(key)}</th><td>${this.renderValue(item)}</td></tr>`
        )
        .join('');
      return `<table class="front-matter-table"><tbody>${rows}</tbody></table>`;
    }
    return `<span class="front-matter-scalar">${escapeHtml(JSON.stringify(value) ?? '')}</span>`;
  }

  getPreferencesSchema(): PluginPreferencesSchema {
    return {
      version: 1,
      sections: [
        {
          id: 'front-matter',
          title: 'Front Matter',
          fields: [
            {
              key: 'expanded',
              type: 'boolean',
              label: 'Expanded by default',
              description:
                'Show the front matter table open. Collapsing or expanding it in a document remembers your choice.',
              defaultValue: DEFAULT_FRONT_MATTER_PREFERENCES.expanded,
            },
          ],
        },
      ],
    };
  }

  onPreferencesChange(preferences: unknown): void {
    if (preferences && typeof preferences === 'object') {
      const prefs = preferences as Partial<FrontMatterPreferences>;
      if (typeof prefs.expanded === 'boolean') {
        this.preferences.expanded = prefs.expanded;
      }
    }
  }

  getStyles(): string {
    return `
      /* Front matter */
      .front-matter {
        margin: 0 0 24px;
        border: 1px solid var(--border-color);
        border-radius: 6px;
        background-color: var(--front-matter-bg);
        font-size: 0.9em;
      }

      .front-matter-summary {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 6px 12px;
        cursor: pointer;
        font-weight: 600;
        color: var(--text-muted);
        user-select: none;
        -webkit-user-select: none;
      }

      .front-matter-summary::marker,
      .front-matter-summary::-webkit-details-marker {
        color: var(--text-muted);
      }

      .front-matter-count {
        font-weight: 400;
        font-size: 0.9em;
        opacity: 0.8;
      }

      .front-matter-body {
        padding: 0 12px 10px;
      }

      .front-matter-table {
        width: 100%;
        margin: 0;
        border-collapse: collapse;
      }

      .front-matter-table th,
      .front-matter-table td {
        padding: 4px 8px;
        border: 1px solid var(--border-color);
        text-align: left;
        vertical-align: top;
        background: transparent;
      }

      .front-matter-table th {
        width: 1%;
        white-space: nowrap;
        font-weight: 600;
        font-family: var(--doc-font-mono);
        font-size: 0.92em;
        color: var(--text-muted);
      }

      .front-matter-table .front-matter-table {
        margin: 0;
      }

      .front-matter-list {
        margin: 0;
        padding-left: 1.2em;
      }

      .front-matter-list > li + li {
        margin-top: 2px;
      }

      .front-matter-null {
        color: var(--text-muted);
      }

      .front-matter-boolean,
      .front-matter-number,
      .front-matter-date {
        font-family: var(--doc-font-mono);
        font-size: 0.92em;
      }

      .front-matter-raw,
      .front-matter-text {
        margin: 0;
        padding: 6px 8px;
        font-size: 0.92em;
        white-space: pre-wrap;
      }
    `;
  }

  getThemeVariables(): PluginThemeDeclaration {
    return {
      'front-matter-bg': {
        light: '#f6f8fa',
        dark: '#161b22',
        description: 'Background of the front matter block',
      },
    };
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Factory function for creating the plugin
 */
export function createFrontMatterPlugin(): MarkdownPlugin {
  return new FrontMatterPlugin();
}
